### ISSUE TITLE
Can't create instance variable for "country-name"

### ISSUE THREAD

**Issue by wkurosawa** [jcouture/ogp#1]
I'm having a problem when trying to parse a page with a tag `og:country-name`:
```
*** NameError Exception: `@country-name' is not allowed as an instance variable name
```
(example: https://www.kao.co.jp/liese/lineup/sugami/)

Ruby doesn't support hyphen when creating a instance variable, so should we change the code to snake_case tag names before trying to instance?

**Comment by jcouture** [comment]
Hi,

Thanks for taking the time to report this behaviour to me.

I see you came up with a solution on your fork.

Are you willing to create a proper pull request  for your patch along with some unit tests?

We could merge it in the official repository and release a new version of the gem.

Kind regards,

**Comment by wkurosawa** [comment]
@jcouture Yes, I wasn't sure if "snake_casing" was the desired solution so I decided to fork and make a quick solution to solve temporarily.
But we ended up using other gem as we were having other issues with other website addresses too. (e.g. missing required attributes raise exception)

**Comment by jcouture** [comment]
@wkurosawa, thanks for sharing your experience with OGP.

What could be tweaked in OGP that would allow you to use it instead of the other solution?

Regards,
